// Wedding guest list. Edit this file to update guests.
// Each guest: { first, last, name, table (1-16), meal, dietary (string or null) }
// NOTE: placeholder data — replace with the real guest list before the event.
window.SEATING_DATA = {
  "guests": [
  {"first":"Olivia","last":"Khan","name":"Olivia Khan","table":1,"meal":"Filet & Wild Mushroom","dietary":"Gluten-Free"},
  {"first":"Liam","last":"Romano","name":"Liam Romano","table":2,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Amara","last":"Abbas","name":"Amara Abbas","table":3,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Noah","last":"Holloway","name":"Noah Holloway","table":4,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Priya","last":"Marlowe","name":"Priya Marlowe","table":5,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Ethan","last":"Ellison","name":"Ethan Ellison","table":6,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Sofia","last":"Rivera","name":"Sofia Rivera","table":7,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Arjun","last":"Castillo","name":"Arjun Castillo","table":8,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Maya","last":"Rahman","name":"Maya Rahman","table":9,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Lucas","last":"Saleh","name":"Lucas Saleh","table":10,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Zara","last":"Hartley","name":"Zara Hartley","table":11,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Mateo","last":"Kapoor","name":"Mateo Kapoor","table":12,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Aaliyah","last":"Nguyen","name":"Aaliyah Nguyen","table":13,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Henry","last":"Iyer","name":"Henry Iyer","table":14,"meal":"Pan-Seared Branzino","dietary":"Gluten-Free"},
  {"first":"Leila","last":"Larsen","name":"Leila Larsen","table":15,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Caleb","last":"Banerjee","name":"Caleb Banerjee","table":16,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Nora","last":"Reyes","name":"Nora Reyes","table":1,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Idris","last":"Bennett","name":"Idris Bennett","table":2,"meal":"Pan-Seared Branzino","dietary":"No Shellfish"},
  {"first":"Elena","last":"Sharma","name":"Elena Sharma","table":3,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Omar","last":"Greenwood","name":"Omar Greenwood","table":4,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Ruby","last":"Fairbanks","name":"Ruby Fairbanks","table":5,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Theo","last":"Pemberton","name":"Theo Pemberton","table":6,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Anika","last":"Nasser","name":"Anika Nasser","table":7,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Julian","last":"Ahmed","name":"Julian Ahmed","table":8,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Imran","last":"Malik","name":"Imran Malik","table":9,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Rohan","last":"Sorensen","name":"Rohan Sorensen","table":10,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Clara","last":"Qureshi","name":"Clara Qureshi","table":11,"meal":"Herb-Roasted Chicken","dietary":"Gluten-Free"},
  {"first":"Dev","last":"Siddiqui","name":"Dev Siddiqui","table":12,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Isla","last":"Sterling","name":"Isla Sterling","table":13,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Sami","last":"Okafor","name":"Sami Okafor","table":14,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Hana","last":"Whitfield","name":"Hana Whitfield","table":15,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Felix","last":"Costa","name":"Felix Costa","table":16,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Yasmin","last":"Vance","name":"Yasmin Vance","table":1,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Owen","last":"Chaudhry","name":"Owen Chaudhry","table":2,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Naomi","last":"Patel","name":"Naomi Patel","table":3,"meal":"Herb-Roasted Chicken","dietary":"No Shellfish"},
  {"first":"Kiran","last":"Caldwell","name":"Kiran Caldwell","table":4,"meal":"Garden Risotto","dietary":"Vegetarian"},
  {"first":"Stella","last":"Donovan","name":"Stella Donovan","table":5,"meal":"Filet & Wild Mushroom","dietary":null},
  {"first":"Asad","last":"Mehta","name":"Asad Mehta","table":6,"meal":"Pan-Seared Branzino","dietary":null},
  {"first":"Vera","last":"Joshi","name":"Vera Joshi","table":7,"meal":"Herb-Roasted Chicken","dietary":null},
  {"first":"Jonah","last":"Vaughn","name":"Jonah Vaughn","table":8,"meal":"Garden Risotto","dietary":"Vegetarian"}
  ]
};
