// Wedding guest list. Edit this file to update guests.
// Each guest: { first, last, name, table (1-17), dietary (string or null) }
// Seating assignments ingested from the WeddingWire seating chart.
// Table 17 is the Sweetheart table. dietary is null until populated per person.
window.SEATING_DATA = {
  "guests": [
  {"first":"Eric","last":"Chen","name":"Eric Chen","table":1,"dietary":null},
  {"first":"Max","last":"Froehlich","name":"Max Froehlich","table":1,"dietary":null},
  {"first":"Michelle","last":"Fan","name":"Michelle Fan","table":1,"dietary":null},
  {"first":"Alexandra","last":"Wu","name":"Alexandra Wu","table":1,"dietary":"gluten-free"},
  {"first":"Ali Zain","last":"Ali","name":"Ali Zain Ali","table":1,"dietary":null},
  {"first":"Salman","last":"Sultan Ali","name":"Salman Sultan Ali","table":1,"dietary":null},
  {"first":"Yuxin","last":"Dong","name":"Yuxin Dong","table":1,"dietary":null},
  {"first":"Wally","last":"Kern","name":"Wally Kern","table":1,"dietary":null},
  {"first":"Ameya","last":"Gadkari","name":"Ameya Gadkari","table":1,"dietary":null},
  {"first":"Elena","last":"González Prieto","name":"Elena González Prieto","table":1,"dietary":null},
  {"first":"Philipp","last":"Srivastava","name":"Philipp Srivastava","table":1,"dietary":null},
  {"first":"Ali Mohammad","last":"Suleman","name":"Ali Mohammad Suleman","table":8,"dietary":null},
  {"first":"Fiza","last":"Khowaja","name":"Fiza Khowaja","table":8,"dietary":null},
  {"first":"Sidra","last":"Muhammadi","name":"Sidra Muhammadi","table":8,"dietary":null},
  {"first":"Owais","last":"Valliani","name":"Owais Valliani","table":8,"dietary":null},
  {"first":"Nayla","last":"Punjabi","name":"Nayla Punjabi","table":8,"dietary":null},
  {"first":"Rafeel","last":"Gillani","name":"Rafeel Gillani","table":8,"dietary":null},
  {"first":"Rayyan","last":"Gillani","name":"Rayyan Gillani","table":8,"dietary":null},
  {"first":"Aish","last":"Wadhwania","name":"Aish Wadhwania","table":3,"dietary":null},
  {"first":"Poorvi","last":"Modi","name":"Poorvi Modi","table":3,"dietary":"vegetarian"},
  {"first":"Irfan","last":"Mithani","name":"Irfan Mithani","table":3,"dietary":null},
  {"first":"Aatifa","last":"Mithani","name":"Aatifa Mithani","table":3,"dietary":null},
  {"first":"Ali","last":"Maredia","name":"Ali Maredia","table":3,"dietary":null},
  {"first":"Alisha","last":"Hooda","name":"Alisha Hooda","table":3,"dietary":"vegetarian"},
  {"first":"Arisha","last":"Keshwani","name":"Arisha Keshwani","table":3,"dietary":null},
  {"first":"Kiran","last":"Kalani","name":"Kiran Kalani","table":4,"dietary":null},
  {"first":"Adnan","last":"Muhammad","name":"Adnan Muhammad","table":4,"dietary":null},
  {"first":"Samreen","last":"Kalani","name":"Samreen Kalani","table":4,"dietary":null},
  {"first":"Shahmeer","last":"Khaliqdina","name":"Shahmeer Khaliqdina","table":4,"dietary":null},
  {"first":"Navroz","last":"Vadsaria","name":"Navroz Vadsaria","table":4,"dietary":null},
  {"first":"Arisha","last":"Ali-Vadsaria","name":"Arisha Ali-Vadsaria","table":4,"dietary":null},
  {"first":"Farheen","last":"Hasni","name":"Farheen Hasni","table":4,"dietary":null},
  {"first":"Amira","last":"Sidi","name":"Amira Sidi","table":9,"dietary":null},
  {"first":"Kiyan","last":"Aashiqali","name":"Kiyan Aashiqali","table":9,"dietary":null},
  {"first":"Jamil","last":"Rehemtulla","name":"Jamil Rehemtulla","table":9,"dietary":null},
  {"first":"Sarah","last":"Rehemtulla","name":"Sarah Rehemtulla","table":9,"dietary":null},
  {"first":"Rahima","last":"Jamal","name":"Rahima Jamal","table":9,"dietary":null},
  {"first":"Aalaynah","last":"Nathoo","name":"Aalaynah Nathoo","table":9,"dietary":null},
  {"first":"Zaiba","last":"Dawood","name":"Zaiba Dawood","table":5,"dietary":null},
  {"first":"Anusha","last":"Saleem","name":"Anusha Saleem","table":5,"dietary":null},
  {"first":"Areeb","last":"Chator","name":"Areeb Chator","table":5,"dietary":null},
  {"first":"Alishah","last":"Chator","name":"Alishah Chator","table":5,"dietary":null},
  {"first":"Zeeshan","last":"Vira","name":"Zeeshan Vira","table":5,"dietary":null},
  {"first":"Rahil","last":"Ukani","name":"Rahil Ukani","table":5,"dietary":null},
  {"first":"Abid","last":"Fazal","name":"Abid Fazal","table":5,"dietary":null},
  {"first":"Mahek","last":"Zindani","name":"Mahek Zindani","table":7,"dietary":null},
  {"first":"Laiba","last":"Zindani","name":"Laiba Zindani","table":7,"dietary":null},
  {"first":"Reza","last":"Ali","name":"Reza Ali","table":7,"dietary":null},
  {"first":"Zoha","last":"Boghani","name":"Zoha Boghani","table":7,"dietary":null},
  {"first":"Maaha","last":"Zaveri","name":"Maaha Zaveri","table":7,"dietary":null},
  {"first":"Ali Ammar","last":"Zaveri","name":"Ali Ammar Zaveri","table":7,"dietary":null},
  {"first":"Iqra","last":"Muhammadi","name":"Iqra Muhammadi","table":7,"dietary":null},
  {"first":"Joccelyn","last":"Alvarado","name":"Joccelyn Alvarado","table":6,"dietary":null},
  {"first":"Shayan","last":"Ali","name":"Shayan Ali","table":6,"dietary":null},
  {"first":"Sara","last":"Panjwani","name":"Sara Panjwani","table":6,"dietary":null},
  {"first":"Saman","last":"Khorasi","name":"Saman Khorasi","table":6,"dietary":null},
  {"first":"Sumair","last":"Bhimani","name":"Sumair Bhimani","table":6,"dietary":null},
  {"first":"Alyssa","last":"Bawa","name":"Alyssa Bawa","table":6,"dietary":null},
  {"first":"Suman","last":"Kalani","name":"Suman Kalani","table":2,"dietary":null},
  {"first":"Hunya","last":"Lakhani","name":"Hunya Lakhani","table":2,"dietary":null},
  {"first":"Saadiya","last":"Lakhani","name":"Saadiya Lakhani","table":2,"dietary":null},
  {"first":"Waleed","last":"Shaban","name":"Waleed Shaban","table":2,"dietary":null},
  {"first":"Anusha","last":"Somani","name":"Anusha Somani","table":2,"dietary":null},
  {"first":"Rahim","last":"Rupani","name":"Rahim Rupani","table":2,"dietary":null},
  {"first":"Sobia","last":"Salim","name":"Sobia Salim","table":2,"dietary":"gluten-free"},
  {"first":"Preet","last":"Khowaja","name":"Preet Khowaja","table":10,"dietary":null},
  {"first":"Perbhaat","last":"Khowaja","name":"Perbhaat Khowaja","table":10,"dietary":null},
  {"first":"Aziz Ali","last":"Khowaja","name":"Aziz Ali Khowaja","table":10,"dietary":null},
  {"first":"Ali Hasnain","last":"Lakhani","name":"Ali Hasnain Lakhani","table":10,"dietary":null},
  {"first":"Ahil","last":"Khuwaja","name":"Ahil Khuwaja","table":10,"dietary":null},
  {"first":"Imaan","last":"Hussain","name":"Imaan Hussain","table":10,"dietary":null},
  {"first":"Munazza","last":"Hussain","name":"Munazza Hussain","table":10,"dietary":null},
  {"first":"Ahmer","last":"Gillani","name":"Ahmer Gillani","table":11,"dietary":null},
  {"first":"AD","last":"Khowaja","name":"AD Khowaja","table":11,"dietary":null},
  {"first":"Sumera","last":"Khowaja","name":"Sumera Khowaja","table":11,"dietary":null},
  {"first":"Najma","last":"Hirani","name":"Najma Hirani","table":11,"dietary":null},
  {"first":"Samina","last":"Lakhani","name":"Samina Lakhani","table":11,"dietary":null},
  {"first":"Shanaz","last":"Mithani","name":"Shanaz Mithani","table":11,"dietary":null},
  {"first":"Anwar","last":"Mithani","name":"Anwar Mithani","table":11,"dietary":null},
  {"first":"Saima","last":"Khuwaja","name":"Saima Khuwaja","table":11,"dietary":null},
  {"first":"Noorjehan","last":"Geelani","name":"Noorjehan Geelani","table":11,"dietary":null},
  {"first":"Ayoob","last":"Geelani","name":"Ayoob Geelani","table":11,"dietary":null},
  {"first":"Saira","last":"Hussain","name":"Saira Hussain","table":11,"dietary":null},
  {"first":"Irshad","last":"Hussain","name":"Irshad Hussain","table":11,"dietary":null},
  {"first":"Shireen","last":"Khowaja","name":"Shireen Khowaja","table":11,"dietary":null},
  {"first":"Amin","last":"Muhammadi","name":"Amin Muhammadi","table":11,"dietary":null},
  {"first":"Sumreen","last":"Muhammadi","name":"Sumreen Muhammadi","table":11,"dietary":null},
  {"first":"Laila","last":"Muhammadi","name":"Laila Muhammadi","table":11,"dietary":null},
  {"first":"Kashif","last":"Valliani","name":"Kashif Valliani","table":11,"dietary":null},
  {"first":"Marina","last":"Valliani","name":"Marina Valliani","table":11,"dietary":null},
  {"first":"Ahmed","last":"Chapsi","name":"Ahmed Chapsi","table":12,"dietary":null},
  {"first":"Inaara Kheraj","last":"Chapsi","name":"Inaara Kheraj Chapsi","table":12,"dietary":null},
  {"first":"Shoaib","last":"Mirzad","name":"Shoaib Mirzad","table":12,"dietary":null},
  {"first":"Anila","last":"Khwaja","name":"Anila Khwaja","table":12,"dietary":null},
  {"first":"Naureen","last":"Sajwani","name":"Naureen Sajwani","table":12,"dietary":null},
  {"first":"Rozina","last":"Chapsi","name":"Rozina Chapsi","table":12,"dietary":null},
  {"first":"Wazir","last":"Chapsi","name":"Wazir Chapsi","table":12,"dietary":null},
  {"first":"Sharmin","last":"Laiwala","name":"Sharmin Laiwala","table":13,"dietary":null},
  {"first":"Simon","last":"Baroi","name":"Simon Baroi","table":13,"dietary":null},
  {"first":"Salim","last":"Jamal","name":"Salim Jamal","table":13,"dietary":null},
  {"first":"Rubina","last":"Jamal","name":"Rubina Jamal","table":13,"dietary":null},
  {"first":"Amin","last":"Alidina","name":"Amin Alidina","table":13,"dietary":null},
  {"first":"Naila","last":"Alidina","name":"Naila Alidina","table":13,"dietary":null},
  {"first":"Amir","last":"Chator","name":"Amir Chator","table":13,"dietary":null},
  {"first":"Jahanara","last":"Chator","name":"Jahanara Chator","table":13,"dietary":null},
  {"first":"Saleem","last":"Dewani","name":"Saleem Dewani","table":13,"dietary":null},
  {"first":"Seema","last":"Dewani","name":"Seema Dewani","table":13,"dietary":null},
  {"first":"Fayaz","last":"Hirji","name":"Fayaz Hirji","table":13,"dietary":null},
  {"first":"Afsheen","last":"Hirji","name":"Afsheen Hirji","table":13,"dietary":null},
  {"first":"Ali Jan","last":"Khowaja","name":"Ali Jan Khowaja","table":14,"dietary":null},
  {"first":"Aliza","last":"Khowaja","name":"Aliza Khowaja","table":14,"dietary":null},
  {"first":"Mehrin","last":"Zindani","name":"Mehrin Zindani","table":14,"dietary":null},
  {"first":"Sophia","last":"Boghani","name":"Sophia Boghani","table":14,"dietary":null},
  {"first":"Fareed","last":"Boghani","name":"Fareed Boghani","table":14,"dietary":null},
  {"first":"Saleena","last":"Boghani","name":"Saleena Boghani","table":14,"dietary":null},
  {"first":"Roohina","last":"Zaveri","name":"Roohina Zaveri","table":14,"dietary":null},
  {"first":"Kashif","last":"Zaveri","name":"Kashif Zaveri","table":14,"dietary":null},
  {"first":"Awais","last":"Lakhani","name":"Awais Lakhani","table":14,"dietary":null},
  {"first":"Anam","last":"Lakhani","name":"Anam Lakhani","table":14,"dietary":null},
  {"first":"Shireen","last":"Suleman","name":"Shireen Suleman","table":14,"dietary":null},
  {"first":"Suleman","last":"Khowaja","name":"Suleman Khowaja","table":14,"dietary":null},
  {"first":"Karima","last":"Gilani","name":"Karima Gilani","table":14,"dietary":null},
  {"first":"Rosemin","last":"Jiwa","name":"Rosemin Jiwa","table":15,"dietary":null},
  {"first":"Alnoor","last":"Sidi","name":"Alnoor Sidi","table":15,"dietary":null},
  {"first":"Shana","last":"Sidi","name":"Shana Sidi","table":15,"dietary":null},
  {"first":"Remti","last":"Lalani","name":"Remti Lalani","table":15,"dietary":null},
  {"first":"Tasneem","last":"Remtulla","name":"Tasneem Remtulla","table":15,"dietary":null},
  {"first":"Shyroze","last":"Rehemtulla","name":"Shyroze Rehemtulla","table":15,"dietary":null},
  {"first":"Alnawaz","last":"Rehemtulla","name":"Alnawaz Rehemtulla","table":15,"dietary":null},
  {"first":"Gulbanu","last":"Nathoo","name":"Gulbanu Nathoo","table":15,"dietary":null},
  {"first":"Suleman","last":"Nathoo","name":"Suleman Nathoo","table":15,"dietary":null},
  {"first":"Gulshan","last":"Rehemtulla","name":"Gulshan Rehemtulla","table":15,"dietary":null},
  {"first":"Abdul","last":"Thawer","name":"Abdul Thawer","table":15,"dietary":null},
  {"first":"Farida","last":"Thawer","name":"Farida Thawer","table":15,"dietary":null},
  {"first":"Salim","last":"Nathoo","name":"Salim Nathoo","table":15,"dietary":null},
  {"first":"Khanum","last":"Nathoo","name":"Khanum Nathoo","table":15,"dietary":null},
  {"first":"Mehboob","last":"Nathoo","name":"Mehboob Nathoo","table":15,"dietary":null},
  {"first":"Linda","last":"Domingo","name":"Linda Domingo","table":15,"dietary":null},
  {"first":"Nazir","last":"Nathoo","name":"Nazir Nathoo","table":15,"dietary":null},
  {"first":"Salma","last":"Aashiqali","name":"Salma Aashiqali","table":16,"dietary":null},
  {"first":"Aamir","last":"Aashiqali","name":"Aamir Aashiqali","table":16,"dietary":null},
  {"first":"Narmeen","last":"Nanji","name":"Narmeen Nanji","table":16,"dietary":null},
  {"first":"Nimroz","last":"Thawer","name":"Nimroz Thawer","table":16,"dietary":null},
  {"first":"Habiba","last":"Thawer","name":"Habiba Thawer","table":16,"dietary":null},
  {"first":"Aadil","last":"Nathoo","name":"Aadil Nathoo","table":16,"dietary":null},
  {"first":"Alidah","last":"Nathoo","name":"Alidah Nathoo","table":16,"dietary":null},
  {"first":"Asra","last":"Muhammadi","name":"Asra Muhammadi","table":17,"dietary":"no-chocolate"},
  {"first":"Nabeel","last":"Rehemtulla","name":"Nabeel Rehemtulla","table":17,"dietary":null}
  ]
};
